let value = 123;
console.log(typeof value);
let value2 = 34.23;
console.log(typeof value2);
let test = 12 / 0;
console.log(typeof test);
console.log(test);
let test2=1/"one";
console.log(test2);
console.log(typeof test2);